apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-webapp
  template:
    metadata:
      labels:
        app: go-webapp
    spec:
      containers:
      - name: go-webapp
        image: go-webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: go-webapp-service
  namespace: production
spec:
  selector:
    app: go-webapp
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer